### ISSUE TITLE
In Windows

### ISSUE THREAD

**Issue by akash-vartak** [saru95/GRE.py#1]
How do you suppose I do it for Windows??
Could you help me out there.

Help ME MAKE one for Windows...

**Comment by kingroryg** [comment]
Its just a python script . runs anywhere .
So you basically need to know 2 things for making this run : 
1. Running a cron job in Windows
2. Triggering a notification for Windows

**Comment by akash-vartak** [comment]
Okaaay, I know about cron tabs, but not how to create them...Can i use windows Task Scheduler??
Rookie here...

**Comment by akash-vartak** [comment]
hey please tell me all the line numbers I would need to change for windows.

**Comment by kingroryg** [comment]
Line 22 for notification triggering .

**Comment by akash-vartak** [comment]
hmm.
